import 'package:device_info_plus/device_info_plus.dart';

Map<String, dynamic> toMap(AndroidDeviceInfo data) => {
      'version.securityPatch': data.version.securityPatch,
      'version.sdkInt': data.version.sdkInt,
      'version.release': data.version.release,
      'version.previewSdkInt': data.version.previewSdkInt,
      'version.incremental': data.version.incremental,
      'version.codename': data.version.codename,
      'version.baseOS': data.version.baseOS,
      'board': data.board,
      'bootloader': data.bootloader,
      'brand': data.brand,
      'device': data.device,
      'display': data.display,
      'fingerprint': data.fingerprint,
      'hardware': data.hardware,
      'host': data.host,
      'id': data.id,
      'manufacturer': data.manufacturer,
      'model': data.model,
      'product': data.product,
      'supported32BitAbis': data.supported32BitAbis,
      'supported64BitAbis': data.supported64BitAbis,
      'supportedAbis': data.supportedAbis,
      'tags': data.tags,
      'type': data.type,
      'isPhysicalDevice': data.isPhysicalDevice,
      'systemFeatures': data.systemFeatures,
      'displaySizeInches':
          ((data.displayMetrics.sizeInches * 10).roundToDouble() / 10),
      'displayWidthPixels': data.displayMetrics.widthPx,
      'displayWidthInches': data.displayMetrics.widthInches,
      'displayHeightPixels': data.displayMetrics.heightPx,
      'displayHeightInches': data.displayMetrics.heightInches,
      'displayXDpi': data.displayMetrics.xDpi,
      'displayYDpi': data.displayMetrics.yDpi,
      'serialNumber': data.serialNumber,
    };
